
version: '2'
services:
  db:
    image: mysql:5.7
    container_name: music163
    restart: always
    ports:
      - "3333:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=music163
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      main:
        aliases:
          - music163
networks:
  main: