spring:
  datasource:
      url: jdbc:mysql://localhost:3306/musicTest?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: 472561212
      driver-class-name: com.mysql.jdbc.Driver
flyway:
  locations: classpath:/db.migration
  url: jdbc:mysql://localhost:3306/musicTest?useUnicode=yes&characterEncoding=UTF-8
  user: root
  password: 472561212